# Generated by Django 5.2.8 on 2025-11-10 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='公司名称')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('website', models.URLField(blank=True, verbose_name='网站')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户公司',
                'verbose_name_plural': '客户公司',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要联系人')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='orders.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'ordering': ['-is_primary', 'name'],
                'unique_together': {('company', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_number', models.CharField(max_length=50, unique=True, verbose_name='询单号')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('quoted', '已报价'), ('confirmed', '客户已确认'), ('rejected', '客户拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('delivery_requirement', models.CharField(blank=True, max_length=200, verbose_name='交货期要求')),
                ('our_lead_time', models.CharField(blank=True, max_length=200, verbose_name='我方报工期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.contact', verbose_name='联系人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '询单',
                'verbose_name_plural': '询单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('material_name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('material_grade', models.CharField(blank=True, max_length=100, verbose_name='材料牌号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='件', max_length=50, verbose_name='单位')),
                ('specifications', models.TextField(blank=True, verbose_name='技术规格')),
                ('drawing_file', models.FileField(blank=True, null=True, upload_to='drawings/', verbose_name='图纸')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(USD)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.inquiry', verbose_name='询单')),
            ],
            options={
                'verbose_name': '询单明细',
                'verbose_name_plural': '询单明细',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('created', '已创建'), ('pending', '待确认'), ('confirmed', '已确认（生产中）'), ('ready', '待提货'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='created', max_length=20, verbose_name='状态')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='发货日期')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('payment_status', models.CharField(blank=True, max_length=50, verbose_name='付款状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.contact', verbose_name='联系人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('material_name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('material_grade', models.CharField(blank=True, max_length=100, verbose_name='材料牌号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='件', max_length=50, verbose_name='单位')),
                ('specifications', models.TextField(blank=True, verbose_name='技术规格')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(USD)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
    ]
