# Generated by Django 5.2.8 on 2025-11-10 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='our_lead_time',
        ),
        migrations.RemoveField(
            model_name='inquiryitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='登录账号'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='customer_notes',
            field=models.TextField(blank=True, verbose_name='客户备注'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报价时间'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='报价人'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quoted_lead_time',
            field=models.CharField(blank=True, max_length=200, verbose_name='报工期'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='supplier_notes',
            field=models.TextField(blank=True, verbose_name='供应商备注'),
        ),
        migrations.AddField(
            model_name='inquiryitem',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='报价单价(USD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, verbose_name='客户备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.inquiry', verbose_name='关联询单'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_notes',
            field=models.TextField(blank=True, verbose_name='供应商备注'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.contact', verbose_name='询价联系人'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='delivery_requirement',
            field=models.CharField(blank=True, max_length=200, verbose_name='客户交货期要求'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', '待报价'), ('quoted', '已报价'), ('accepted', '客户已接受'), ('rejected', '客户已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='drawing_file',
            field=models.FileField(blank=True, null=True, upload_to='drawings/inquiries/', verbose_name='图纸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.contact', verbose_name='下单联系人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计交货日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未付款'), ('partial', '部分付款'), ('paid', '已付款')], default='unpaid', max_length=20, verbose_name='付款状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际发货日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认（生产中）'), ('ready', '待提货'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
