# Generated by Django 5.2.8 on 2025-11-10 08:11

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_contact_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='drawing_file',
            field=models.FileField(blank=True, help_text='可选：单个图纸快速上传。复杂工件请使用下方"订单附件"上传多个文件', null=True, upload_to='drawings/orders/%Y/%m/', validators=[orders.models.validate_file_extension, orders.models.validate_file_size], verbose_name='图纸文件'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='drawing_file',
            field=models.FileField(blank=True, help_text='可选：单个图纸快速上传。复杂工件请使用下方"询单附件"上传多个文件', null=True, upload_to='drawings/inquiries/%Y/%m/', validators=[orders.models.validate_file_extension, orders.models.validate_file_size], verbose_name='图纸文件'),
        ),
        migrations.CreateModel(
            name='InquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/inquiries/%Y/%m/', validators=[orders.models.validate_file_extension, orders.models.validate_file_size], verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='文件描述')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.inquiry', verbose_name='询单')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '询单附件',
                'verbose_name_plural': '询单附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/orders/%Y/%m/', validators=[orders.models.validate_file_extension, orders.models.validate_file_size], verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='文件描述')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order', verbose_name='订单')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '订单附件',
                'verbose_name_plural': '订单附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
