# Generated by Django 5.2.8 on 2025-11-10 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_drawing_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='contact',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批准时间'),
        ),
        migrations.AddField(
            model_name='contact',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contacts', to=settings.AUTH_USER_MODEL, verbose_name='批准人'),
        ),
        migrations.AddField(
            model_name='contact',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='拒绝原因'),
        ),
    ]
