# Generated by Django 5.2.8 on 2025-11-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('buyer', '买家'), ('supplier', '供应商')], default='buyer', max_length=20, verbose_name='角色'),
        ),
    ]
