# Generated by Django 5.2.8 on 2025-11-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_contact_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='客户订单号'),
        ),
    ]
