# Generated by Django 5.2.8 on 2025-11-18 09:29

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_customer_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.inquiry', verbose_name='关联询单')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order', verbose_name='关联订单')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '沟通消息',
                'verbose_name_plural': '沟通消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/messages/%Y/%m/', validators=[orders.models.validate_file_extension, orders.models.validate_file_size], verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名称')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.message', verbose_name='消息')),
            ],
            options={
                'verbose_name': '消息附件',
                'verbose_name_plural': '消息附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
